# Gitlab CI to build docker images
variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker login --username $username --password $password

build-cron:
  stage: build
  script:
    - cd Cron/
    - chmod 755 build.sh
    - ./build.sh

build-nginx:
  stage: build
  script:
    - apk update
    - apk add openssl
    - cd Nginx/
    - chmod 755 build.sh
    - ./build.sh

build-php:
  stage: build
  script:
    - cd PHP/
    - chmod 755 build.sh
    - ./build.sh

build-Traefik:
  stage: build
  script:
    - cd Traefik
    - chmod 755 build.sh
    - ./build.sh
