stages:
  - build

build-cron:
  stage: build
  script:
    - cd Cron/
    - docker login --username $username --password $password
    - docker build --tag djpic/cron:standard .
    - docker tag djpic/cron:standard djpic/cron:latest
    - cd default
    - docker build --tag djpic/cron:default .
    - docker push djpic/cron:latest
    - docker push djpic/cron:standard
    - docker push djpic/cron:default

build-nginx:
  stage: build
  script:
    - cd Nginx/
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh

build-php:
  stage: build
  script:
    - cd PHP/
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh

build-Traefik:
  stage: build
  script:
    - cd Traefik
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh