stages:
  - build

build-cron:
  stage: build
  script:
    - cd Cron/
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh

build-nginx:
  stage: build
  script:
    - cd Nginx/
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh

build-php:
  stage: build
  script:
    - cd PHP/
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh

build-Traefik:
  stage: build
  script:
    - cd Traefik
    - docker login --username $username --password $password
    - chmod 755 build.sh
    - ./build.sh