# reference http://www.inanzzz.com/index.php/post/su76/creating-apache-mysql-and-php-fpm-containers-for-a-web-application-with-docker-compose
FROM httpd:2.4-alpine

COPY default.conf /usr/local/apache2/conf/httpd.conf

