name: Check for updates to base image
on: workflow_dispatch

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Get latest release of this repo
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: 11matt556
          repo: socat-cron
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: alpine/socat:${{ steps.keydb.outputs.release }}
          image: 11matt556/socat-cron:${{ steps.keydb.outputs.release }}

  update-action:
    if: needs.check.outputs.needs-updating == 'true'
    needs: check-for-update
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Updated base image of cron-socat available"
        # Check if issue has already been created
        # Create issue stating update is available if issue has not already been created
        # List available tags from base image in the issue

