name: Push changes to Gitlab
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github repo
      uses: actions/checkout@v3
      
    - name: Push to Gitlab repo
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "11matt556@users.noreply.github.com"
        git remote set-url origin "https://oauth2:${{ secrets.GITLAB_PROJECT_TOKEN }}@gitlab.com/11matt556/cron-socat.git"
        git remote add old https://github.com/11matt556/cron-socat.git
        git fetch --unshallow old
        git push origin master --force
