name: Publish Docker image
on: workflow_dispatch

env:
  ALPINE_SOCAT_VERSION: 1.7.4.4
  
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build
        run: ./build.sh {{ $env.ALPINE_SOCAT_VERSION }}
      - name: Publish to GitHub
        run: | 
              docker push ghcr.io/11matt556/socat-cron:latest
              docker push ghcr.io/11matt556/socat-cron:${{ env.ALPINE_SOCAT_VERSION }}
              
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub 
        run: |
              docker push docker.io/11matt556/socat-cron:latest
              docker push docker.io/11matt556/socat-cron:${{ env.ALPINE_SOCAT_VERSION }}
