name: Publish Docker image
on: workflow_dispatch

env:
  ALPINE_SOCAT_VERSION: 1.7.4.4
  DOCKER_HUB: docker.io/11matt556/socat-cron
  GITHUB_CONTAINER: ghcr.io/11matt556/socat-cron
  
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
              docker build --build-arg alpine_socat_version=${{ env.ALPINE_SOCAT_VERSION }} --tag ${{ env.GITHUB_CONTAINER }}:${{ env.ALPINE_SOCAT_VERSION }} --tag ${{ env.GITHUB_CONTAINER }}:latest . 
              docker build --build-arg alpine_socat_version=${{ env.ALPINE_SOCAT_VERSION }} --tag ${{ env.DOCKER_HUB }}:${{ env.ALPINE_SOCAT_VERSION }}       --tag ${{ env.DOCKER_HUB }}:latest  . 

      - name: Publish to GitHub
        run: | 
              docker push ${{ env.GITHUB_CONTAINER }}:latest
              docker push ${{ env.GITHUB_CONTAINER }}:${{ env.ALPINE_SOCAT_VERSION }}
              
      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub 
        run: |
              docker push ${{ env.DOCKER_HUB }}:latest
              docker push ${{ env.DOCKER_HUB }}:${{ env.ALPINE_SOCAT_VERSION }}
